---
# defaults file for kubelet
kubelet:
  extraArgs:
    - "--anonymous-auth=false"
    - "--authorization-mode=Webhook"
    - "--allowed-unsafe-sysctls=net.*"
    - "--network-plugin=cni"
  log:
    level: 1