- name: Distribution CA certificate
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    checksum: "{{ item.checksum }}"
    owner: root
    group: root
    timeout: 3
  retries: 3
  with_items:
    - {
        url: "{{ PKI_URL }}/{{ PROJECT_NAME }}/{{ PROJECT_ENV }}/cilium.crt",
        dest: "/etc/kubernetes/pki/cilium.crt",
        checksum: "sha256:{{ PKI_URL }}/{{ PROJECT_NAME }}/{{ PROJECT_ENV }}/cilium.crt.sha256sum",
        mode: 644
      }
    - {
        url: "{{ PKI_URL }}/{{ PROJECT_NAME }}/{{ PROJECT_ENV }}/cilium.key",
        dest: "/etc/kubernetes/pki/cilium.key",
        checksum: "sha256:{{ PKI_URL }}/{{ PROJECT_NAME }}/{{ PROJECT_ENV }}/cilium.key.sha256sum",
        mode: 600
      }
    - {
        url: "{{ PKI_URL }}/{{ PROJECT_NAME }}/{{ PROJECT_ENV }}/hubble-relay.crt",
        dest: "/etc/kubernetes/pki/hubble-relay.crt",
        checksum: "sha256:{{ PKI_URL }}/{{ PROJECT_NAME }}/{{ PROJECT_ENV }}/hubble-relay.crt.sha256sum",
        mode: 644
      }
    - {
        url: "{{ PKI_URL }}/{{ PROJECT_NAME }}/{{ PROJECT_ENV }}/hubble-relay.key",
        dest: "/etc/kubernetes/pki/hubble-relay.key",
        checksum: "sha256:{{ PKI_URL }}/{{ PROJECT_NAME }}/{{ PROJECT_ENV }}/hubble-relay.key.sha256sum",
        mode: 600
      }
    - {
        url: "{{ PKI_URL }}/{{ PROJECT_NAME }}/{{ PROJECT_ENV }}/hubble-server.crt",
        dest: "/etc/kubernetes/pki/hubble-server.crt",
        checksum: "sha256:{{ PKI_URL }}/{{ PROJECT_NAME }}/{{ PROJECT_ENV }}/hubble-server.crt.sha256sum",
        mode: 644
      }
    - {
        url: "{{ PKI_URL }}/{{ PROJECT_NAME }}/{{ PROJECT_ENV }}/hubble-server.key",
        dest: "/etc/kubernetes/pki/hubble-server.key",
        checksum: "sha256:{{ PKI_URL }}/{{ PROJECT_NAME }}/{{ PROJECT_ENV }}/hubble-server.key.sha256sum",
        mode: 600
      }
  tags:
    - renew
    - update