---
# handlers file for kube-proxy
- name: restarted kube-proxy
  ansible.builtin.systemd:
    name: kube-proxy
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: 
    - KUBE_ACTION != "deploy" 
    - KUBE_ACTION != "scale"

- name: Clean kube-proxy csr
  ansible.builtin.file:
    path: /etc/kubernetes/pki/kube-proxy.csr
    state: absent