---
# handlers file for etcd
- name: restarted etcd
  ansible.builtin.systemd:
    name: etcd
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: 
    - KUBE_ACTION != "deploy" 
    - KUBE_ACTION != "scale"

- name: Clean etcd server csr
  ansible.builtin.file:
    path: /etc/kubernetes/pki/etcd/server.csr
    state: absent

- name: Clean etcd peer csr
  ansible.builtin.file:
    path: /etc/kubernetes/pki/etcd/peer.csr
    state: absent

- name: Clean etcd healthcheck csr
  ansible.builtin.file:
    path: /etc/kubernetes/pki/etcd/healthcheck-client.csr
    state: absent